### ISSUE TITLE
Ability to mirror svg horizontally

### ISSUE THREAD

**Issue by sedbytes** [SyedAhkam/glyph-studio#10]
This would improve the UX when trying to play the glyphs solely looking at the back of the phone.

**Comment by Aleks-Levet** [comment]
The image I sent you have nice big clickable areas, you could do that, right?

**Comment by sedbytes** [comment]
@Aleks-Levet This has been taken care of, please download a new build from https://nightly.link/SyedAhkam/glyph-studio/workflows/build/master?preview

After installing, try toggling the mirroring mode option from preferences, and report back please.

**Comment by Aleks-Levet** [comment]
Hi, 
I just installed it, and the mirroring function works! 
But the clickable areas are still too tiny, you have to press exactly on the glyph...

**Comment by sedbytes** [comment]
Cool, @Aleks-Levet 

Your clickable area issue has been acknowledged, sadly it isn't too easy to implement based on the way I load and render glyph paths. 

Allow me some time to figure out a way to make that happen. Continue in #11.
