### ISSUE TITLE
It's not working on Np1...

### ISSUE THREAD

**Issue by Aleks-Levet** [SyedAhkam/glyph-studio#9]

**Comment by sedbytes** [comment]
Hi, could you elaborate please? what have you tried and what didn't work as expected?

**Comment by Aleks-Levet** [comment]
So on my (non rooted) nothing phone 1, the glyph are not lighting up...

Here's a screen recording:

https://drive.google.com/file/d/1OFP4El8BVDAyGwtaDSLPPnpnxxiZKZqV/view?usp=drivesdk

**Comment by Aleks-Levet** [comment]
Also it's hard to press the glyphs

**Comment by sedbytes** [comment]
Thanks for the screen recording. Just to be sure, you have enabled the glyph debugging mode right?

**Comment by Aleks-Levet** [comment]
Hey, I enabled the glyph debug mode, and it works!!

But it's real hard to press on the glyphs.

Also is it possible to mirror the glyphs buttons? (Add an option on the settings) So I can look at the back of my phone and watch the glyphs?

**Comment by sedbytes** [comment]
That's great to hear! @Aleks-Levet 

Yeah, I'm aware of the touchable area being small. I still am yet to find a good way to solve that issue.

What do you mean by mirroring? Perhaps what you want is the flows feature, if you click on "Create New" from the sidebar, you'll be able to record a set of actions, save, and then play them all just by clicking the play button.

**Comment by sedbytes** [comment]
Ah I think I understood what you mean by mirroring. I'll see if I can get that feature implemented. #10

**Comment by Aleks-Levet** [comment]
By mirroring I mean this:

![Screenshot_20241010-120800](https://github.com/user-attachments/assets/839eac58-6255-4ae4-8c66-9c43457524d8)

**Comment by sedbytes** [comment]
Yep, I got it. Thanks for the suggestion @Aleks-Levet!

**Comment by sedbytes** [comment]
Please continue in #10, I'm closing this.
